/** @type {import('prettier').Config} */
module.exports = {
  endOfLine: "lf",
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "all",
  printWidth: 120,
  arrowParens: "avoid",
  importOrder: [
    "^(express/(.*)$)|^(express$)",
    "<THIRD_PARTY_MODULES>",
    "^types$",
    "^@config(.*)$",
    "^@services/(.*)$",
    "^@/controllers/(.*)$",
    "^@/types/(.*)$",
    "^@/utils/(.*)$",
    "^@/constants/(.*)$",
    "^@/libs/(.*)$",
    "^[./]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: false,
  importOrderCombineTypeAndValueImports: true,
  plugins: ["@ianvs/prettier-plugin-sort-imports"],
};
